name: Check code style

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - actions

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Repository checkout
    - uses: actions/setup-node@v2
      name: Node Setup
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm run lint
